check if _.filter returns a non empty array before retrieving any value from it
maxjerin/communis-ui pull request #7
Opened 2020-10-22 03:52 UTC by jmathewt

2020-10-22 04:28 UTC, maxjerin requested changes

2020-10-22 04:28 UTC, maxjerin commented on src/transformers/workerTransfomer.js
> +        ? _.isEmpty(_.filter(worker.contacts, ['type', 'CELL_PHONE']))
What if we build a common method for this (or something better)?

```
getContactField(contacts, field) {
  if (contacts) {
      var value = _.isEmpty(_.filter(worker.contacts, ['type', 'CELL_PHONE'])) ?
         ? null
         : _.filter(worker.contacts, ['type', 'CELL_PHONE'])[0].value
      return value
  } else {
    return null
  }
}
```

2020-10-22 13:41 UTC, jmathewt commented on src/transformers/workerTransfomer.js
> +        ? _.isEmpty(_.filter(worker.contacts, ['type', 'CELL_PHONE']))
Makes sense. Changes made. Can you review again?

2020-10-22 14:37 UTC, maxjerin commented on src/transformers/workerTransfomer.js
> +      cellPhone: retrieveContact(worker.contacts, ['type', 'CELL_PHONE']),
Since `retrieveContact` is only meant to get contacts, we can omit sending `type` to the method and only send 'CELL_PHONE' and other values. What do you think?

2020-10-23 14:47 UTC, jmathewt commented on src/transformers/workerTransfomer.js
> +      cellPhone: retrieveContact(worker.contacts, ['type', 'CELL_PHONE']),
Hey that makes sense. I have pushed the changes

2020-10-23 15:01 UTC, maxjerin approved these changes

2020-10-23 15:09 UTC, merged